# Generated by Django 5.2.8 on 2025-11-17 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('hora_chegada', models.DateTimeField()),
                ('hora_saida', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.usuario')),
            ],
            bases=('core.usuario',),
        ),
        migrations.CreateModel(
            name='Cozinha',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.usuario')),
            ],
            bases=('core.usuario',),
        ),
        migrations.CreateModel(
            name='Garcom',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.usuario')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='garcons', to='core.restaurante')),
            ],
            bases=('core.usuario',),
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.usuario')),
            ],
            bases=('core.usuario',),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ingredientes', models.TextField()),
                ('preco', models.FloatField()),
                ('disponivel_na_cozinha', models.BooleanField(default=True)),
                ('cardapio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.cardapio')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas', to='core.mesa')),
                ('caixas', models.ManyToManyField(blank=True, related_name='contas', to='core.caixa')),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoCartao',
            fields=[
                ('pagamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pagamento')),
                ('nro_transacao', models.IntegerField()),
            ],
            bases=('core.pagamento',),
        ),
        migrations.CreateModel(
            name='PagamentoCheque',
            fields=[
                ('pagamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pagamento')),
                ('numero', models.IntegerField()),
            ],
            bases=('core.pagamento',),
        ),
        migrations.CreateModel(
            name='PagamentoDinheiro',
            fields=[
                ('pagamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pagamento')),
            ],
            bases=('core.pagamento',),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='conta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='core.conta'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('horario_pedido', models.DateTimeField()),
                ('horario_entrega', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.cliente')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='core.conta')),
                ('cozinha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas', to='core.cozinha')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('item_cardapio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='core.itemcardapio')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='mesa',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='core.restaurante'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='garcom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mesas', to='core.garcom'),
        ),
        migrations.AddField(
            model_name='cardapio',
            name='gerente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cardapio', to='core.gerente'),
        ),
    ]
