# Generated by Django 5.2.8 on 2025-12-10 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_garcom_restaurante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='gerente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cardapio', to='core.gerente'),
        ),
    ]
